### ISSUE TITLE
crashes with google calendar files

### ISSUE THREAD

**Issue by may-cat** [oberron/pyICSParser#7]
```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    testLoader()
  File "test.py", line 13, in testLoader
    dates = mycal.get_event_instances(dtstart,dtend)
  File "/mnt/c/web/all.bitbucket/pyICSParser-0.6a14/build/lib.linux-x86_64-2.7/pyICSParser/pyiCalendar.py", line 1821, in get_event_instances
    self.parse_loaded()
  File "/mnt/c/web/all.bitbucket/pyICSParser-0.6a14/build/lib.linux-x86_64-2.7/pyICSParser/pyiCalendar.py", line 960, in parse_loaded
    self.Validator("3.6.1_1", line_count = line_count, line = line, level = 1,show=True) #raise Exception("VCALENDAR VALIDATOR","encountered END:%s instead of END:%s @line: %s"%(closing_Component,Component_Name,str(line_count)))
  File "/mnt/c/web/all.bitbucket/pyICSParser-0.6a14/build/lib.linux-x86_64-2.7/pyICSParser/pyiCalendar.py", line 769, in Validator
    raise Exception("RFC5545 non compliance","RFC5545 specifies: \'%s\', following line is not compliant \n line: %s - %s"%(RFC5545_SCM[RFC_SCM],str(line_count),line))
Exception: ('RFC5545 non compliance', 'RFC5545 specifies: \'\xc2\xa73.6.1 specifies that \'The "VEVENT" calendar component cannot be nested within another calendar component.\', following line is not compliant \n line: 18 - END:VTIMEZONE')
```

**Comment by oberron** [comment]
[may-cat](https://github.com/may-cat) FYI: the latest package on pypi 0.7.4 https://pypi.org/project/pyICSParser/ has a fix which fixes this issue (based on py3, if you need the py2.7 patch let me know)
